### ISSUE TITLE
Pulse 15 touchpad LED now working in Manjaro Cinnamon

### ISSUE THREAD

**Issue by simonpw** [tuxedocomputers/tuxedo-touchpad-switch#11]
On my Pulse 15 under Manjaro Cinnamon the touchpad activation and deactivation are working but the status LED does not.

tuxedo-touchpad-switch 1.0.4-1
linux 5.16.14-1-MANJARO
cinnamon 5.2.7

Please let me know what information you need.

Thanks

Simon

**Comment by Matombo** [comment]
Cinnamon is not supported.

But feel free to fork and add support for it. In theory it shouldn't be far away from gnome.
