### ISSUE TITLE
[BUG] Touchpad light not working properly after login.

### ISSUE THREAD

**Issue by onurbbr** [tuxedocomputers/tuxedo-touchpad-switch#12]
Touchpad light turns on at login screen but blinks after login. GNOME Shell opens the closed touchpad for about 2 seconds, while tuxedo-touchpad-switch sees the touchpad as open. At the 3rd second, gnome-shell turns off the touchpad, but tuxedo-touchpad-switch cannot see this operation. So you need to add 3 second delay for your program to run properly. I temporarily added the following command to /etc/xdg/autostart/tuxedo-touchpad-switch.desktop and the touchpad light works fine.

Exec=sh -c 'sleep 3; tuxedo-touchpad-switch'

(NOTE: The problem is not in the login screen(GDM). After login(GNOME Shell).)

**Comment by Matombo** [comment]
I can't reproduce it on Ubuntu 22.04. Which version of gnome are you running?

**Comment by juancherru** [comment]
Can't make it work on Ubuntu 22.04 on Wayland. If I start the session on Xorg, the led turns on when I disable the touchpad from gnome config app.
Double tapping on the phisical touchpad doesn´t do nothing.
The laptop is a XPG Xenia 14, I think is  a TongFang ID4H1 o so.
Edit: Gnome version is 42.2

**Comment by onurbbr** [comment]
> I can't reproduce it on Ubuntu 22.04. Which version of gnome are you running?

I'm using Ubuntu 22.04 too.
Gnome 42.2

**Comment by juancherru** [comment]
Hi! No news on this?

**Comment by Matombo** [comment]
Obviously not yet ;)
But be assured the issue is not forgotten and hanging out on my todo list.

**Comment by Matombo** [comment]
> Can't make it work on Ubuntu 22.04 on Wayland. If I start the session on Xorg, the led turns on when I disable the touchpad from gnome config app. Double tapping on the phisical touchpad doesn´t do nothing. The laptop is a XPG Xenia 14, I think is a TongFang ID4H1 o so. Edit: Gnome version is 42.2

The double tapping should work independent of this package.
What this packages does is sending the disable information from the desktop environment to the touchpads firmware, which then also disables and turns the led on.

However this second disable is optional (we just do it because it's the only way to turn the led on).

**Comment by Matombo** [comment]
@juancherru Maybe you are missing tuxedo-keyboard? That is required for all the fn shortcuts and also the double tab touchpad disable to work.

**Comment by Matombo** [comment]
Can't reproduce on Gnome 42.4, assume fixed, please tell me if not.
