### ISSUE TITLE
Build for openSUSE?

### ISSUE THREAD

**Issue by Hacker-Planet** [tuxedocomputers/tuxedo-touchpad-switch#14]
I was wondering if the build instructions could be applied to RPM distros like openSUSE or even Fedora? If so how would that be possible. Thank you

**Comment by arnoheekhout** [comment]
This is how I did it on Fedora (sometimes the light turns of without a reason): 

1. Open a terminal and install the necessary development libraries and tools by running the following command:
```sudo dnf install gcc-c++ cmake make libudev-devel glib2-devel```

2. Clone the repository by running the following command:
```git clone https://github.com/tuxedocomputers/tuxedo-touchpad-switch.git```

3. Navigate to the cloned repository by running the following command:
```cd tuxedo-touchpad-switch```

4. Create a build directory and navigate into it by running the following commands:
```mkdir build```
```cd build```

5. Generate the build files by running the following command:
cmake ..

6. Build the software by running the following command:
```make```

7. Install the software by running the following command:
```sudo make install```

**Comment by Hacker-Planet** [comment]
I will have to give this a shot. Thank you for your input on this.
