### ISSUE TITLE
Tried to install on Arch KDE

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [tuxedocomputers/tuxedo-touchpad-switch#5]
Hey,

I have tried to install this on Arch KDE, followed the README instructions but it didn't work. I'm using the `Slimbook Pro X 15`. There are some targets related to KDE on the `Makefile`:

- setup-kde.o
- setup-kde.i
- setup-kde.s

Do I need to do anything else?
Thanks,
MiguelNdeCarvalho

**Comment by Matombo** [comment]
Can you be more specific what exactly didn't work?

**Comment by Matombo** [comment]
Closed because of inactivity.
