### ISSUE TITLE
[BUG] [CRITICAL] Touchpad is not working after sleep mode on Arch Linux Plasma Desktop. 

### ISSUE THREAD

**Issue by onurbbr** [tuxedocomputers/tuxedo-touchpad-switch#9]
I installed tuxedo-touchpad-switch via aur. I am using KDE Plasma version 5.24. When I wake the device from sleep mode, the touchpad light turns on, but I cannot activate the touchpad. Although the touchpad appears to be enabled in KDE, the touchpad does not work. I didn't get any log, but if you tell me how to get log, I can send log.

**Comment by reallybadjoke** [comment]
Same problem here. I use kernel  5.15.22-1-lts.

**Comment by effeffe** [comment]
Same here. I had to remove the package until it gets resolved. Issues from 5.15 onwards

**Comment by brainpower** [comment]
Pretty sure Kernel version is irrelevant here. Something probably changed in kde's `solid` or `kded` with plasma 5.24 that triggers this bug.
Do you see any errors when killing the autostarted `tuxedo-touchpad-switch` and running it manually in a terminal, then suspend and resume? 
That could help find the issue.

For me it prints this when starting, but nothing before or after suspending.
It seems to indicate something is failing to initialize though:
```
$ tuxedo-touchpad-switch
kded5_modules_touchpad_handler(...): g_dbus_proxy_call_sync(...) failed.
main(...): kded5_modules_touchpad_init(...) failed.
```
maybe the dbus interface changed?

**Comment by ashwinvis** [comment]
I tried 2 different Tuxedo OEM kernels on KDE Neon (`linux-oem-20.04{c,d}`). I also tried to disable the software level 
"Toggle Touchpad" shortcut in KDE's System Settings. It does not help.

I found two workarounds so far and both independently restores touchpad.

- Logout and login again
- Execute `tuxedo-touchpad-switch` on terminal and interrupt using Ctrl+C.

**Comment by brainpower** [comment]
ok, I was right, the object-path of the dbus thing changed with the new plasma.
Instead of "/modules/touchpad" it is now "/modules/kded_touchpad"
changing https://github.com/tuxedocomputers/tuxedo-touchpad-switch/blob/master/setup-kde.cpp#L168 accordingly fixes the issue.

I've found that by calling `qdbus org.kde.kded5 ` to list the object-paths kded5 has.
I have no idea how to integrate this in a backwards compatible way though, I've never used glib2.

**Comment by Matombo** [comment]
Thanks for the detective work.
I will set an update on my todo list. No ETA however.

**Comment by brainpower** [comment]
oh, still looking at the objects and methods kded has on dbus,
I think it may be as easy as doing (in pseudocode):
```
loadedModules = dbus_call("org.kde.kded5", "/kded", "org.kde.kded5.loadedModules")
if(loadedModules.contains("kded_touchpad"))
  object_path = "kded_touchpad"
else if (loadedModules.contains("touchpad"))
  object_path = "touchpad"
else
  cerr << "could not find touchpad module in kded. Is it disabled?\n"
```
I could try to rig that up tonight and do a PR if that approach is ok? (And I'll learn some glib2 stuff, which will probably be useful at some point ...)

**Comment by brainpower** [comment]
Another thing I noticed, the return value of `setup_kde()` (or `setup_gnome()` for that matter) is not checked here:
 https://github.com/tuxedocomputers/tuxedo-touchpad-switch/blob/master/tuxedo-touchpad-switch.cpp#L107

If tuxedo-touchpad-switch had checked and exited if setup failed, people wouldn't have ended up with disabled touchpads, I think.
So it should probably exit if setup fails? Or is there any reason not to do that?

**Comment by onurbbr** [comment]
> ok, I was right, the object-path of the dbus thing changed with the new plasma. Instead of "/modules/touchpad" it is now "/modules/kded_touchpad" changing https://github.com/tuxedocomputers/tuxedo-touchpad-switch/blob/master/setup-kde.cpp#L168 accordingly fixes the issue.
> 
> I've found that by calling `qdbus org.kde.kded5 ` to list the object-paths kded5 has. I have no idea how to integrate this in a backwards compatible way though, I've never used glib2.

You're right. Now I see it in the logs. Thanks. I'll wait for the next update for now.

**Comment by Matombo** [comment]
Version 1.0.4 now live on TUXEDO_OS repos.
